### ISSUE TITLE
#PROGRESS 3 - MEMBUAT SOFTWARE DESIGN

### ISSUE THREAD

**Issue by daniakiki** [daniakiki/project-akhir-SmokeDetector#11]
Buatlah sketsa tampilan dashboard blynk

**Comment by akbarfadila** [comment]
![WhatsApp Image 2023-05-30 at 5 46 12 PM](https://github.com/daniakiki/project-akhir-SmokeDetector/assets/124494200/bd837e10-d42f-4bff-bd4a-9aa89040e10c)

**Comment by akbarfadila** [comment]
![SAVE_20230530_175132](https://github.com/daniakiki/project-akhir-SmokeDetector/assets/124494200/1ebf6c39-1adf-44dc-af06-a73b688bca20)

**Comment by akbarfadila** [comment]
Wireframe Blynk Mobile
![Desain tanpa judul (4) (1)](https://github.com/daniakiki/project-akhir-SmokeDetector/assets/124494200/f978aac9-6520-4c29-a74c-75865332f29a)
![Desain tanpa judul (2)](https://github.com/daniakiki/project-akhir-SmokeDetector/assets/124494200/ffa03ed8-78e5-4624-a54c-8fd0dd1b929c)

**Comment by akbarfadila** [comment]
Wireframe Blynk WEB Desktop
![WhatsApp Image 2023-05-30 at 8 54 38 PM](https://github.com/daniakiki/project-akhir-SmokeDetector/assets/124494200/15bb9f33-19a8-4510-abd0-bfa12971566c)

![Desain tanpa judul (3)](https://github.com/daniakiki/project-akhir-SmokeDetector/assets/124494200/369fe436-71c4-4cd2-a861-9e97988bfa97)

**Comment by akbarfadila** [comment]
Wireframe WEB Desktop
![Desain tanpa judul (3)](https://github.com/daniakiki/project-akhir-SmokeDetector/assets/124494200/7974bb92-82dc-4bef-b539-4cf1bd201396)


![WhatsApp Image 2023-05-30 at 8 54 38 PM](https://github.com/daniakiki/project-akhir-SmokeDetector/assets/124494200/af7662a2-3c0b-4fb5-a4bc-050817389dd9)

**Comment by akbarfadila** [comment]
wireframe tampilan telegram
![TELEGRAM](https://github.com/daniakiki/project-akhir-SmokeDetector/assets/124494200/6415056d-f01c-43e1-93ba-bd601602ab3a)
![TAMPILAN TELEGRAM](https://github.com/daniakiki/project-akhir-SmokeDetector/assets/124494200/0a9f2b02-f708-436f-97a3-79f25783dd23)

**Comment by akbarfadila** [comment]
![image](https://github.com/daniakiki/project-akhir-SmokeDetector/assets/124494200/85ef561c-27fe-4805-8ace-bd47de92594d)
![image](https://github.com/daniakiki/project-akhir-SmokeDetector/assets/124494200/77080554-95eb-49c1-8b7e-9aa06f65a0cb)
