### ISSUE TITLE
#PROGRESS 3 - MEMBUAT FIRMWARE DESIGN (ALAT)

### ISSUE THREAD

**Issue by daniakiki** [daniakiki/project-akhir-SmokeDetector#12]
buatlah flowchart alat yang akan dibuat

**Comment by ayunisari1406** [comment]
![SMART SMOKE DETECTOR](https://github.com/daniakiki/project-akhir-SmokeDetector/assets/126434881/9e66cd4e-3bb1-4eaa-bd54-301941ca05a3)

FLOWCHART ALAT
