### ISSUE TITLE
#PROGRESS 3 - MEMBUAT FIRMWARE DESIGN (BLYNK)

### ISSUE THREAD

**Issue by daniakiki** [daniakiki/project-akhir-SmokeDetector#14]
buatlah flowchart koneksi ke blynk

**Comment by Intanchyaa** [comment]
Flowchart Blynk

**Comment by Intanchyaa** [comment]
![Flowchart BYLINK  (1)](https://github.com/daniakiki/project-akhir-SmokeDetector/assets/130478222/ad16bf29-4de1-477c-afe7-f939c3de655a)

**Comment by Intanchyaa** [comment]
![Uploading Team document.png…]()

**Comment by Intanchyaa** [comment]
![Team document](https://github.com/daniakiki/project-akhir-SmokeDetector/assets/130478222/12f06eb6-4cda-459b-90f4-2bde73cc7281)
