### ISSUE TITLE
#PROGRESS 3 - MEMBUAT NOTIFIKASI TELEGRAM

### ISSUE THREAD

**Issue by daniakiki** [daniakiki/project-akhir-SmokeDetector#16]
buatlah kalimat notifikasi yang akan dikirimkan ke telegram pada setiap kondisi

**Comment by Intanchyaa** [comment]
JIKA SENSOR MENDETEKSI KETEBALAN ASAP ROKOK TIPIS, MAKA NOTIFIKASI PESAN YANG AKAN DIKIRIM MELALUI TELEGRAM ADALAH : CAUTION : KAWASAN INI MEMILIKI KETEBALAN ASAP ROKOK YANG TIPIS!

JIKA SENSOR MENDETEKSI KETEBALAN ASAP ROKOK SEDANG, MAKA NOTIFIKASI PESAN YANG AKAN DIKIRIM MELALUI TELEGRAM ADALAH : WARNING : KAWASAN INI MEMILIKI KETEBALAN ASAP ROKOK YANG SEDANG!

JIKA SENSOR MENDETEKSI KETEBALAN ASAP ROKOK TEBAL, MAKA NOTIFIKASI PESAN YANG AKAN DIKIRIM MELALUI TELEGRAM ADALAH : DANGER : KAWASAN INI MEMILIKI KETEBALAN ASAP ROKOK YANG TEBAL! TOLONG TINGGALKAN KAWASAN INI!
