### ISSUE TITLE
#PROGRESS 4 - MEMBUAT CODE AKTIFKAN BLOWER

### ISSUE THREAD

**Issue by ayunisari1406** [daniakiki/project-akhir-SmokeDetector#17]
Membuat program codingan untuk mengaktifkan blower

**Comment by Intanchyaa** [comment]
const int smokePin = 14;       // Pin analog untuk membaca tingkat kepadatan asap
const int relayPin = 12;       // Pin digital untuk mengendalikan relay


void setup() {
  pinMode(smokePin, INPUT);
  pinMode(relayPin, OUTPUT);
}

void loop() {
  // Baca tingkat kepadatan asap
  int smokeLevel = analogRead(smokePin);

  // Tentukan kecepatan blower berdasarkan tingkat kepadatan asap
  if (smokeLevel>=10 && smokeLevel<200) {
    // Asap tipis, matikan blower
    digitalWrite(relayPin, LOW);
  } else if (smokeLevel>=200 && smokeLevel<400) {
    // Asap sedang, aktifkan blower 
    digitalWrite(relayPin, HIGH);
  } else if (smokeLevel>=400) {
    // Asap tebal, aktifkan blower 
    digitalWrite(relayPin, HIGH);
    
  }

  delay(1000);  // Tunggu 1 detik sebelum membaca tingkat kepadatan asap selanjutnya
}
