### ISSUE TITLE
#PROGRESS 4 - MEMBUAT CODE PEMBACAAN SENSOR MQ135

### ISSUE THREAD

**Issue by ayunisari1406** [daniakiki/project-akhir-SmokeDetector#18]
Membuat program codingan untuk pemebacaan sensor MQ135

**Comment by AlfithoSatya** [comment]
#include "MQ135.h"

#define SENSOR 34

void setup()
{
  Serial.begin(9600);
    delay(5000);
}


  void loop()
  {
    MQ135 gasSensor = MQ135(SENSOR);
    float air_quality = gasSensor.getPPM();
    if(air_quality>=10 && air_quality<200){
    Serial.print("Air Quality: ");  
    Serial.print(air_quality);
    Serial.println("  PPM");   
    Serial.println("--Kondisi Aman--");

    Serial.println("Waiting...");
    }
    if(air_quality>=200 && air_quality<400){
    Serial.print("Air Quality: ");  
    Serial.print(air_quality);
    Serial.println("  PPM");   
    Serial.println("--Kondisi terdapat asap rokok--");

    Serial.println("Waiting...");
    }

    if(air_quality>=400){
    Serial.print("Air Quality: ");  
    Serial.print(air_quality);
    Serial.println("  PPM");   
    Serial.println("--Kondisi terdapat asap rokok tidak wajar--");

    Serial.println("Waiting...");

    }
      delay(2000);  
}
