### ISSUE TITLE
#PROGRESS 1 - Membuat Masalah, Batasan Masalah, dan Rumusan Masalah

### ISSUE THREAD

**Issue by daniakiki** [daniakiki/project-akhir-SmokeDetector#2]
Carilah masalah yang mendasari ide dari project akhir yang dibuat, kemudian buatlah Batasan Masalah dan Rumusan Masalahnya

**Comment by ayunisari1406** [comment]
MASALAH, BATASAN MASALAH, RUMUSAN MASALAH

MASALAH :
BAGAIMANA MERANCANG DAN MENGIMPLEMENTASIKAN SISTEM DETEKSI ASAP CERDAS (IOT) UNTUK RUANGAN TERTUTUP YANG EFEKTIF DAN ANDAL AGAR TERCIPTANYA LINGKUNGAN YANG BEBAS DARI ASAP ROKOK ?

BATASAN MASALAH:
1. SISTEM DETEKSI ASAP CERDAS INI  DIRANCANG KHUSUS UNTUK RUANGAN TERTUTUP TANPA AC.
2. SOLUSI INI AKAN BERFOKUS PADA PENGURANGAN KETEBALAN ASAP PADA SMOKING AREA DAN MEMBERIKAN PERINGATAN DINI TANPA MENGAKTIFKAN SISTEM PEMADAM KEBAKARAN SECARA OTOMATIS.

RUMUSAN MASALAH:
BAGAIMANA MERANCANG DAN MENGIMPLEMENTASIKAN SISTEM DETEKSI ASAP CERDAS (IOT) UNTUK RUANGAN TERTUTUP YANG EFEKTIF DAN ANDAL, YANG DAPAT MENDETEKSI ASAP DARI ROKOK DENGAN CEPAT DAN AKURAT, MEMBERIKAN NOTIFIKASI REAL-TIME KEPADA PENGUNJUNG, DAN MENGINTEGRASIKAN SENSOR DETEKSI ASAP, MODUL KOMUNIKASI IOT, DAN PERANGKAT LUNAK PENGOLAHAN DATA?
