### ISSUE TITLE
#PROGRESS 4 - MEMBUAT CODE KONEKSI KE BLYNK

### ISSUE THREAD

**Issue by ayunisari1406** [daniakiki/project-akhir-SmokeDetector#20]
Membuat program codingan untuk koneksi ke Blynk

**Comment by akbarfadila** [comment]
#include "MQ135.h"
#include <WiFi.h>
#include <WiFiClient.h>
#include <BlynkSimpleEsp32.h>

#define BLYNK_PRINT Serial

#define SENSOR 34

#define BLYNK_TEMPLATE_ID "TMPL6sVnqvd-q"
#define BLYNK_TEMPLATE_NAME "FINAL PROJECT"
#define BLYNK_AUTH_TOKEN "Iw72qVjDvYYoK3WdAQpmB9mEDPxiMqmF"

BlynkTimer timer;


char ssid[] = "ALIF";
char pass[] = "alifsofyan02";

float air_quality;


void myTimerEvent(){
  Blynk.virtualWrite(V0, air_quality);

  if(air_quality >=10 && air_quality <= 200){
           Blynk.virtualWrite(V2, 1);
 }  else {Blynk.virtualWrite(V2, 0);}

 if(air_quality >400 && air_quality <= 1000){
 Blynk.virtualWrite(V5, 1);}
   else {Blynk.virtualWrite(V5, 0);}

     if(air_quality >200 && air_quality <= 400){
       Blynk.virtualWrite(V4, 1);
     }  else {Blynk.virtualWrite(V4, 0);}
    }



void setup()
{
  Serial.begin(9600);
  Blynk.begin(BLYNK_AUTH_TOKEN, ssid, pass);
  timer.setInterval(1000L, myTimerEvent);
  pinMode(18, OUTPUT);
  pinMode(19, OUTPUT);
  pinMode(21, OUTPUT);
  pinMode(SENSOR, INPUT);
}


  void loop()
  {
    MQ135 gasSensor = MQ135(SENSOR);
    air_quality = gasSensor.getPPM();
    Serial.print("Air Quality: ");  
    Serial.print(air_quality);
    Serial.println("  PPM");   

    Serial.println("Waiting...");

    Blynk.run();
    timer.run();
}
