### ISSUE TITLE
#PROGRESS 1 - MENCARI KEUNIKAN YANG DIBERIKAN OLEH PROJEK AKHIR

### ISSUE THREAD

**Issue by daniakiki** [daniakiki/project-akhir-SmokeDetector#4]
Carilah sesuatu hal yang akan menjadi keunikan dari project akhir ini, serta berikan penjelasannya

**Comment by akbarfadila** [comment]
KEUNIKAN YANG DIBERIKAN
Led untuk notifikasi ketebalan Asap
"menggunakan led sebagai indikator ketebalan asap rokok memberikan keunikan visual yang mudah dipahami. Led digunakan dalam berbagai warna yang berbeda untuk mengindikasikan tingkat kepadatan asap rokok". 
Misalnya :
LED berwarna merah menunjukkan ketebalan asap yang sangat tebal
LED berwarna kuning menunjukkan ketebalan asap yang sedang
LED berwarna Hijau menunjukkan ketebalan asap yang  Tipis.
Hal Ini bertujuan untuk memberikan informasi visual yang jelas kepada pengguna tentang tingkat kepadatan asap di sekitar detektor.

**Comment by Intanchyaa** [comment]
KEUNIKAN YANG DIBERIKAN : 
Blower sebagai penghisap asap : penggunaan blower sebagai penghisap asap rokok adalah keunikan yang membedakan proyek ini dari detektor asap konvensional. Blower yang terpasang pada detektor dapat secara aktif menghisap asap rokok dari area merokok, mengurangi penyebarannya ke lingkungan sekitar. Hal ini membantu mengjaga kebersihan udara sekitar area merokok dan mengurangi resiko masuknya asap ke ruangan lain.
