### ISSUE TITLE
#PROGRESS 2 - MENJELASKAN FITUR YANG DIGUNAKAN

### ISSUE THREAD

**Issue by daniakiki** [daniakiki/project-akhir-SmokeDetector#6]
Jelaskan tentang fitur apa saja yang digunakan dalam platform IoT yang sudah dipilih (Blynk)

**Comment by akbarfadila** [comment]
Kelompok kami memilih Blynk karena platform IoT ini gratis dan memungkinkan pengguna untuk mengontrol dan memantau perangkat IoT melalui aplikasi web dan mobile. pada aplikasi Blynk menawarkan beberapa fitur yang berguna untuk monitoring asap dengan ESP32. Beberapa fitur yang dapat digunakan dalam platform Blynk untuk tujuan kelompok kami adalah sebagai berikut:

- Aplikasi Mobile: Blynk menyediakan aplikasi mobile yang dapat digunakan pada sistem operasi iOS dan Android. Aplikasi ini memungkinkan pengguna untuk dengan mudah mengakses dan mengontrol perangkat IoT.

- Integrasi dengan ESP32: Blynk mendukung integrasi dengan berbagai perangkat, termasuk ESP32 yang kami gunakan. Platform ini memungkinkan penggunaan ESP32 sebagai modul perangkat keras yang terhubung dengan Blynk untuk mengirimkan data dari sensor asap ke aplikasi Blynk
Dapatkan Token Autentikasi FIRMWARE CONFIGURATION: projek kelompok yang akan dibuat di Blynk akan diberikan token autentikasi unik. Token ini diperlukan untuk menghubungkan ESP32 dengan projek Blynk yang telah di buat nanti nya. Dapatkan token autentikasi ini dari menu home di aplikasi Blynk.

- Widget Blynk: Blynk menyediakan berbagai widget yang dapat digunakan dalam aplikasi Blynk untuk memantau asap. Beberapa widget yang berguna dalam konteks ini meliputi:
               Gauge: Widget ini memungkinkan tampilan tingkat asap dalam bentuk grafik atau angka.
               Value Display: Widget ini digunakan untuk menampilkan nilai asap dalam bentuk angka.
               LED: Widget ini dapat menunjukkan kondisi asap dengan menghidupkan atau mematikan LED berdasarkan tingkat 
                         kepekatan asap yang terdeteksi.
             Misalnya LED berwarna merah menunjukkan ketebalan asap yang sangat tebal
            LED berwarna kuning menunjukkan ketebalan asap yang sedang
             LED berwarna Hijau menunjukkan ketebalan asap yang Tipis.
 Hal Ini bertujuan untuk memberikan informasi visual yang jelas kepada pengguna tentang tingkat kepadatan asap di sekitar detektor.

Dengan menggunakan fitur-fitur ini, kelompok kami dapat memanfaatkan platform Blynk untuk memantau asap dengan ESP32. Aplikasi mobile Blynk memungkinkan pengguna untuk mengakses perangkat IoT ini dengan mudah, sedangkan integrasi dengan ESP32 memungkinkan pengiriman data sensor asap ke aplikasi Blynk. Selain itu, widget-widget Blynk seperti Gauge, Value Display, dan LED dapat membantu dalam memvisualisasikan dan memantau tingkat asap yang terdeteksi pada projek kami.
- Fitur blower sebagai penghisap asap rokok memberikan keunggulan berupa penghisapan aktif untuk mengurangi ketebalan asap rokok dari suatu ruangan dan mengurangi penyebaran asap ke ruangan lain sehingga meningkatkan kenyamanan dengan lingkungan yang bebas dari asap dan bau rokok. Dengan demikian, blower sebagai penghisap asap rokok memberikan solusi efektif dalam menjaga kualitas udara dan melindungi kesehatan orang banyak.
- Dalam projek ini, kami juga menyediakan fitur pemberitahuan melalui Telegram kepada pengunjung berupa notifikasi, sehingga mereka dapat memantau situasi dan tingkat kepadatan asap di lokasi tersebut.
