### ISSUE TITLE
#PROGRESS 2 -  MENJELASKAN INTERFACE MIKROKONTROLLER

### ISSUE THREAD

**Issue by daniakiki** [daniakiki/project-akhir-SmokeDetector#7]
Jelaskan interface mikrokontroler apa saja yang digunakan untuk project akhir, misalkan menggunakan WIFI/Bluetooth untuk koneksinya,ADC,DAC,PWM,dll

**Comment by AlfithoSatya** [comment]
Interface mikrokontroller yang ingin kita pakai adalah 
1.menggunakan koneksi Wifi, dikarenakan project yang ingin kita buat yaitu memonitoring asap pada suatu ruangan untuk memberikan notifikasi yang akan disampaikan kepada user, maka dari itu kita membutuhkan koneksi Wifi yang akan terhubung langsung ke internet. 
Salah satu website untuk interface tersebut yang akan kita pakai yaitu menggunakan Blynk.cloud, kegunaan dari website ini adalah kita dapat menghubungkan perangkat mikrokontroller yang kita pakai untuk terhubung ke internet sehingga dapat memonitoring hasil yang kita inginkan dari jauh.
2.Smoke detector sensor (MQ135), sensor ini dipakai sebagai inti dari project kami untuk mendeteksi asap rokok disekitar.Sensor ini dapat mendeteksi gas amonia (NH3), natrium-(di)oksida (NOx), alkohol / ethanol (C2H5OH), benzena (C6H6), karbon dioksida (CO2), gas belerang / sulfur-hidroksida (H2S) dan gas - gas lainnya yang ada di atmosfer. 
Sensor MQ135 ini akan terhubung ke esp 32 yang dimana cara kerja nya yaitu sensor mengirim sinyal tegangan analaog yang di convert menjadi sinyal tegangan digital (ADC) dan menghasilkan ppm(besaran  yang diinginkan). Dari hasil/keluaran ppm tersebut lah kita dapat membuat parameter yang bertujuan untuk memonitoring asap yang di ruangan tersebut.
