### ISSUE TITLE
#PROGRESS 2 - MENJELASKAN MIKROKONTROLLER YANG DIGUNAKAN

### ISSUE THREAD

**Issue by daniakiki** [daniakiki/project-akhir-SmokeDetector#8]
Jelaskan tentang mikrokontroler yang digunakan pada project akhir (ESP32) dan alasannya menggunakan mikrokontroler ini

**Comment by ayunisari1406** [comment]
DALAM PROJEK INI KAMI INGIN MENGGUNAKAN ESP32 SEBAGAI MIKROKONTROLLERNYA. ADAPUN BEBERAPA ALASAN PEMILIHAN MIKROKONTROLLER TERSEBUT DALAM PROJEK SMART SMOKE DETECTOR INI :

1. KINERJA YANG KUAT: ESP32 ADALAH MIKROKONTROLER YANG DILENGKAPI DENGAN DUA INTI PROSESOR BERKECEPATAN 240 MHZ. DENGAN MEMILIKI DUA INTI PROSESOR, ESP32 MEMUNGKINKAN KITA MENJALANKAN BANYAK TUGAS SECARA BERSAMAAN DENGAN KINERJA YANG LEBIH BAIK. INI MEMUNGKINKAN PENGENDALIAN YANG EFEISIEN TERHADAP KOMPONEN LAIN DALAM SISTEM DETEKTOR ASAP PINTAR NANTINYA.

2. MODUL WI-FI DAN BLUETOOTH TERINTEGRASI: ESP32 MEMILIKI MODUL WI-FI DAN BLUETOOTH YANG TERINTEGRASI. DENGAN FITUR INI, DETEKTOR ASAP PINTAR INI DAPAT TERHUBUNG KE JARINGAN WI-FI UNTUK MENGIRIMKAN PEMBERITAHUAN ATAU MENGAKTIFKAN TINDAKAN LAIN MELALUI KONEKSI BLUETOOTH. INI MEMBERIKAN FLEKSIBILITAS DALAM MENYAMBUNGKAN DETEKTOR ASAP KE PERANGKAT LAIN ATAU PLATFORM INTERNET OF THINGS (IOT).

3. KEMAMPUAN PEMROGRAMAN YANG LUAS: ESP32 MENDUKUNG BERBAGAI BAHASA PEMROGRAMAN, TERMASUK ARDUINO IDE DAN BAHASA MICROPYTHON. DENGAN KEMAMPUAN INI, KAMI DAPAT MEMILIH LINGKUNGAN PEMROGRAMAN YANG PALING SESUAI DENGAN KEBUTUHAN PROYEK KAMI. FLEKSIBILITAS INI MEMUNGKINKAN KAMI MENGEMBANGKAN KODE DAN MEMANFAATKAN SUMBER DAYA YANG TERSEDIA UNTUK MENGOPTIMALKAN FUNGSI DETEKTOR ASAP PINTAR.

4. UKURAN KECIL: ESP32 MEMILIKI FAKTOR BENTUK YANG KECIL, MEMUDAHKAN INTEGRASI KE DALAM PROYEK DETEKTOR ASAP KAMI. DENGAN UKURAN YANG KOMPAK, DENGAN INI KAMI DAPAT DENGAN MUDAH MENEMPATKAN MIKROKONTROLER INI DI DALAM PERANGKAT DETEKTOR ASAP TANPA MENGORBANKAN RUANG ATAU DESAIN KESELURUHAN.

5. HARGA YANG TERJANGKAU: ESP32 MERUPAKAN MIKROKONTROLER YANG RELATIF TERJANGKAU DIBANDINGKAN DENGAN BEBERAPA ALTERNATIF LAINNYA. KELEBIHAN INI MEMBUATNYA MENJADI PILIHAN YANG BAIK UNTUK PROYEK-PROYEK HOBI ATAU PROTOTIPE YANG MEMILIKI ANGGARAN TERBATAS. KAMI BERHARAP DAPAT MEMANFAATKAN KINERJA DAN FITUR YANG DITAWARKAN OLEH ESP32 TANPA MENGURAS BANYAK SUMBER DAYA KEUANGAN.

6. KONSUMSI DAYA YANG SANGAT RENDAH: FITUR- FITUR HEMAT DAYA SEPERTI FINE RESOLUTION CLOCK GATING, MULTIPLE POWER MODES, DAN DYNAMIC POWER SCALING MEMUNGKINKAN ESP32 MENGOPTIMALKAN PENGGUNAAN DAYA SESUAI DENGAN KEBUTUHAN SISTEM. HAL INI SANGAT PENTING DALAM PROYEK-PROYEK YANG MEMBUTUHKAN EFEISIENSI ENERGI, SEPERTI DETEKTOR ASAP PINTAR. DENGAN MENGGUNAKAN ESP32, KAMI HARAP DAPAT MERANCANG SISTEM YANG DAPAT BEROPERASI DENGAN LAMA MENGGUNAKAN DAYA YANG MINIMAL, MENINGKATKAN MASA PAKAI BATERAI ATAU MENGURANGI KEBUTUHAN DAYA EKSTERNAL.

REFERENSI 
file:///C:/Users/M415DAO/Downloads/15729-File%20Utama%20Naskah-48381-1-10-20210424%20(1).pdf
https://www.edukasielektronika.com/2019/07/arsitektur-dan-fitur-esp32-module-esp32.html
https://www.anakteknik.co.id/krysnayudhamaulana/articles/apa-itu-esp32-salah-satu-modul-wi-fi-poppuler
https://miqbal.staff.telkomuniversity.ac.id/mikrokontroler-esp32/
