### ISSUE TITLE
#PROGRESS 2 - MEMBUAT ANALISA EKONOMIS TERHADAP PERANGKAT YANG DIPILIH

### ISSUE THREAD

**Issue by daniakiki** [daniakiki/project-akhir-SmokeDetector#9]
Buatlah analisa ekonomis terhadap perangkat yang digunakan, seperti dari harganya, kwalitasnya, ketahanannya,dll

**Comment by Intanchyaa** [comment]
1.	Mikrokontroller ESP32 : ESP32 memiliki kisaran harga RP 65.000/unit. Dalam analisis ekonomis ESP32 digunakan karena harganya yang terjangkau dan cenderung lebih murah. Kemampuanya dapat terkonektivitas dengan wifi dan bluetooth dan kemampuan memproses datanya lebih cepat. Dengan begitu kelompok kami memilih ESP32 karena komponen ini sesuai dan dibutuhkan pada project yang dikerjakan. 
2.	Sensor MQ135 : sensor MQ135 memiliki kisaran harga RP 25.000/unit. Dalam keunggulannya sensor ini memiliki kepekaan relatif tinggi terhadap gas amonia, bensol, alkohol, CO2, smoke dan gas-gas lainnya. selain kegunaanya yang kita pertimbangkan harganya juga yang relatif murah. Sensor ini memiliki daya tahan yang baik untuk penggunaan penanda bahaya asap karena praktis dan tidak memakan daya yang besar Dengan begitu kelompok kami memilih sensor MQ135  karena komponen ini sesuai dan dibutuhkan pada project yang dikerjakan.
3.	Rainbow Cabel Male to Female : Rainbow cabel male to female memiliki kisaran harga RP 13.000/set. Biasanya kabel ini digunakan untuk menghubungkan komponen elektronika  ke breadboard. : Rainbow cabel male to female memiliki konektor di ujungnya yang sangat memudahkan kita dalam memasang maupun melepas kabel ke komponen, harganya terjangkau dan memiliki warna bervariasi yang memudahkan kita dalam membuat rangkaian. Dengan begitu kelompok kami memilih Rainbow cabel male to female  karena kabel ini sesuai dengan kebutuhan project yang dikerjakan.
4.	Buzzer : Buzzer memiliki kisaran harga RP 6.000/unit. Buzzer  merupakan komponen elektronika yang dapat menghasilkan getaran suara berupa gelombang bunyi. buzzer elektronika relatif lebih murah dan lebih mudah untuk digunakan karena tidak memerlukan penguat khusus untuk  menghasilkan suara yang dapat didengar oleh manusia. Dengan begitu kelompok kami memilih Buzzer karena kabel ini sesuai dengan kebutuhan project yang dikerjakan.
5.	Led RGB : Led RGB memiliki kisaran harga RP 2.000/unit. LED RGB membuat indikator dan tampilan yang sangat baik dan murah untuk proyek elektronik. Dapat digunakan untuk menampilkan hampir semua warna pelangi  dan dapat ditenagai oleh voltase rendah.  Dengan begitu kelompok kami memilih Led RGB karena kabel ini sesuai dengan kebutuhan project yang dikerjakan.
6.	Relay : Relay memiliki kisaran harga RP 10.000/unit. Prinsip kerja yang digunakan oleh relay adalah prinsip elektromagnetik sehingga apabila menggunakan low power atau arus listrik yang kecil, relay tetap dapat menghantarkan listrik yang bertegangan lebih tinggi. Memiliki ketahanan yang relatif tinggi. Dengan begitu kelompok kami memilih Relay karena kabel ini sesuai dengan kebutuhan project yang dikerjakan. 
7.	BreadBoard : BreadBoard memiliki kisaran harga RP 12.000/unit. breadboard tidak merusak komponen yang dirakit. Komponen-komponen ini juga dapat dipasang kembali ke sirkuit lain. Breadboard biasanya terbuat dari plastik dan memiliki berbagai lubang. Dapat dengan mudah mengganti dan menambahkan kompenen elektronika yang akan kita gunakan sehingga dapat menghemat waktu dan biaya. Dengan begitu kelompok kami memilih BreadBoard karena kabel ini sesuai dengan kebutuhan project yang dikerjakan.
8.	Kabel (Micro USB  Cable) : Kabel (Micro USB  Cable) memiliki kisaran harga RP 15.000/unit. Kabel (Micro USB  Cable)  digunakan karena harganya yang terjangkau dan cenderung lebih murah. Dengan begitu kelompok kami memilih Kabel (Micro USB  Cable)   karena kabel ini sesuai dengan kebutuhan project yang dikerjakan.

HARGA KOMPONEN :

•	Mikrokontroller ESP32 (65.000)
•	Sensor MQ135 (25.000)
•	Rainbow Cabel Male to Female (13.000)
•	Buzzer (6.000)
•	Led RGB (2.000)
•	Relay (10.000)
•	BreadBoard (12.000)
•	Kabel (Micro USB  Cable) (15.000)
Jumlah : RP 148.000 
Biaya pengerjaan produk = ¼ dari pengerjaan produk. 
Ongkos kirim = 15.000-20.000

Dapat kita analisis bahwa untuk membeli alat yang dibutuhkan untuk project ini menghabiskan biaya sebesar 148.000. sedangkan untuk harga pasaran sebuah smoke detector adalah kisaran RP. 219.000 – 800.000. sehingga jika menggunakan perbandingan harga pasar, kita dapat pasarkan produk yang dibuat kisaran harga RP. 180.000-200.000/unit. Hal tersebut di pertimbangkan  dari fungsi dan juga kelebihan komponen-komponen yang digunakan, selain itu melihat ketahanan dan kualitas dari alat yang dibuat.
